# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'CyberpaySdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CyberpaySdk
    pod 'FittedSheets'
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'MaterialComponents/BottomSheet'
  target 'CyberpaySdkTests' do
    # Pods for testing
  end

end
